config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "grid", to: "words#new"
  post "/words/:grid", to: "words#score"
  get "score", to: "words#score"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/words_controller.rb
require 'open-uri'
require 'json'

class WordsController < ApplicationController
  def new
    @grid = []
    10.times { @grid << ("A".."Z").to_a.sample }
    @grid = @grid.join(" ");
    @grid
  end

  def score
    @word = params[:word]
    @grid = params[:grid]
    @score = 0
    @url = "https://wagon-dictionary.herokuapp.com/#{@word}"
    @user_serialized = URI.open(@url).read
    @user = JSON.parse(@user_serialized)
    if @user["found"] == false
      @answer = "You get 0 points! It is no an english word"
    elsif include?(@grid, @word) == false
      @answer = "Word is not matching the grid"
    else
      @answer = "Good job. You are getting #{@word.length} points"
      @score += @word.length
      session[:score] += @score
    end
    @answer
  end

  def include?(grid, attempt)
    attempt.upcase.scan(/\w/).map do |letter|
      return false unless grid.include?(letter)
    end
    true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/new.html.erb
<h2>What is the biggest word you can make from these letters?</h2>
<h2 class="grid"><%= @grid %></h2>

<div id="box">
  <form action="score">
    <input type="text" name="word">
    <input type="submit" value="Take a try!">
    <%= hidden_field_tag "grid", @grid %>
  </form>
</div>

  <p>Current score: <%= session[:score] %></p>

app/views/words/score.html.erb
<h2 class="grid"><%= @grid %></h2>
<h3>Your word is:   <%= @word %></h3>
<h3>Your score is: <%= @score %> points</h3>
<p><%= @answer %></p>
<p>Current score:<%= session[:score] %></p>

<%= link_to grid_path do%>
  <p id="return-homepage">Play ones more</p>
<%end%>